### ISSUE TITLE
Unescaped left brace in regex

### ISSUE THREAD

**Issue by jirutka** [cmhughes/latexindent.pl#21]
perl 5.21.6 complains about unescaped left braces in regex:

````
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/^\s*\\begin{ <-- HERE document}/ at ./latexindent.pl line 623.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/^\s*%\*\s*\\begin{ <-- HERE (.*?)}/ at ./latexindent.pl line 993.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/^\s*%\*\s*\\end{ <-- HERE (.*?)}/ at ./latexindent.pl line 1019.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/^%\s*\\end{ <-- HERE (.*?)}/ at ./latexindent.pl line 1145.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/^%\s*\\begin{ <-- HERE (.*?)}/ at ./latexindent.pl line 1166.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/^\s*(\$)?\\begin{ <-- HERE \\?(.*?)}/ at ./latexindent.pl line 1567.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/^\s*\\end{ <-- HERE \\?(.*?)}/ at ./latexindent.pl line 1628.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\end{ <-- HERE document}/ at ./latexindent.pl line 1567, <MAINFILE> line 32.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\\end{ <-- HERE example}/ at ./latexindent.pl line 1567, <MAINFILE> line 36.
````

**Comment by cmhughes** [comment]
Just to follow-up, this is high on my list to investigate; I'm doing a bit of an overhaul at the moment, and then hoping to update my perl distribution, at which point I imagine I'll be able to replicate this issue and, hopefully, fix it.

**Comment by cmhughes** [comment]
Thanks again for reporting this. I used `perlbrew` to install `perl v5.22.1` and was able to recreate the errors you describe.

I believe that I have fixed it at https://github.com/cmhughes/latexindent.pl/commit/ce8113329500adb5a65cbccbd9192a05a74f9842. It would be great if you take a look and verify at your end as well (pull from the develop branch).

**Comment by cmhughes** [comment]
I'm closing this issue for the moment, as I believe that it is resolved. Do feel free to follow-up if you find any further problems. Thanks again for reporting this!

**Comment by elspru** [comment]
ummm, I still get the same error, after git cloneing, smae version of perl.

**Comment by cmhughes** [comment]
The master branch hasn't yet been fixed -- I'm working on a new approach
from scratch, hoping for a release in the next 6 months.

In the mean time, try checking out the develop branch :)
